<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>8.0</LangVersion>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup>
		<Description>
			This package includes code .Net Standard EF core data repository and service
			It is part of the Yugen Toolkit.
		</Description>
		<PackageId>Yugen.Toolkit.Standard.Data</PackageId>
		<PackageTags>Yugen Toolkit Data</PackageTags>	
		<Title>$(PackageId)</Title>	
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.31" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.31">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Yugen.Toolkit.Standard.Core\Yugen.Toolkit.Standard.Core.csproj" />
	</ItemGroup>

</Project>
