<Project Sdk="MSBuild.Sdk.Extras">

	<PropertyGroup>
		<TargetFrameworks>uap10.0.26100</TargetFrameworks>
		<LangVersion>8.0</LangVersion>
		<TargetPlatformBaseVersion>10.0</TargetPlatformBaseVersion>
		<TargetPlatformRevision>26100</TargetPlatformRevision>
		<TargetPlatformMinRevision>18362</TargetPlatformMinRevision>
		<TargetPlatformVersion>$(TargetPlatformBaseVersion).$(TargetPlatformRevision).0</TargetPlatformVersion>
		<TargetPlatformMinVersion>$(TargetPlatformBaseVersion).$(TargetPlatformMinRevision).0</TargetPlatformMinVersion>
		<ExtrasUwpMetaPackageVersion>6.2.14</ExtrasUwpMetaPackageVersion>
		<DebugType>Portable</DebugType>
		<GenerateLibraryLayout>true</GenerateLibraryLayout>
		<IsPackable>true</IsPackable>
		<IsPublishable>true</IsPublishable>
		<ExtrasEnableDefaultXamlItems>true</ExtrasEnableDefaultXamlItems>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<Platforms>x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
		<NoWarn>$(NoWarn);NETSDK1023</NoWarn>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Yugen.Toolkit.Uwp.Audio.Services.Abstractions\Yugen.Toolkit.Uwp.Audio.Services.Abstractions.csproj" />
	</ItemGroup>
</Project>