<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
		<UseUwp>true</UseUwp>
		<Platforms>x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
		<DefaultLanguage>en-US</DefaultLanguage>
		<IsAotCompatible>true</IsAotCompatible>
		<DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
	</PropertyGroup>

	<PropertyGroup>
		<Author>panda-sharp</Author>
		<Solution>Yugen.Toolkit</Solution>
		<Project>Yugen.Toolkit.Uwp.Controls</Project>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>$(Project)</PackageId>
		<PackageVersion>1.0.0</PackageVersion>
		<Description>
			This library provides XAML templated controls. It is part of the Yugen Toolkit.

			Controls:
			- Dialogs
			- Graphs
			- Menu
			- Validation
		</Description>
		<Authors>$(Author)</Authors>
		<Title>$(Project)</Title>
		<!--<Company>panda-sharp</Company>-->
		<PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/$(Author)/$(Solution)</PackageProjectUrl>
		<PackageIcon>images\icon.png</PackageIcon>
		<PackageReadmeFile>docs\Readme.md</PackageReadmeFile>
		<!-- <PackageReleaseNotes>releaseNotes</PackageReleaseNotes> -->
		<!-- <Copyright>Copyright</Copyright> -->
		<PackageTags>Yugen Toolkit Uwp Controls XAML Dialogs Graphs Menu Validation</PackageTags>
		<RepositoryUrl>https://github.com/panda-sharp/Yugen.Toolkit.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\Docs\icon.png" Pack="true" PackagePath="\images\" />
		<None Include="..\Readme.md" Pack="true" PackagePath="\docs\" />
		<!-- XAML control -->
		<None Include="bin\Release\$(TargetFramework)\$(Project)\**\*.xaml"
			  PackagePath="\lib\net10.0-windows10.0.26100\$(Project)" 
			  Pack="true" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.UI.Xaml" Version="2.8.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Yugen.Toolkit.Uwp\Yugen.Toolkit.Uwp.csproj" />
		<ProjectReference Include="..\Yugen.Toolkit.Standard\Yugen.Toolkit.Standard.csproj" />
	</ItemGroup>
</Project>