<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>8.0</LangVersion>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup>
		<Description>
			This package includes .Net Standard converters, extension, helpers...
			It is part of the Yugen Toolkit.
		</Description>
		<PackageId>Yugen.Toolkit.Standard</PackageId>
		<PackageTags>Yugen Toolkit Converters Extension Helpers</PackageTags>
		<Title>$(PackageId)</Title>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
		<PackageReference Include="System.Text.Json" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Yugen.Toolkit.Standard.Core\Yugen.Toolkit.Standard.Core.csproj" />
	</ItemGroup>

</Project>
