<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
		<UseUwp>true</UseUwp>
		<Platforms>x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
		<DefaultLanguage>en-US</DefaultLanguage>
		<IsAotCompatible>true</IsAotCompatible>
		<DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
	</PropertyGroup>

	<PropertyGroup>
		<Author>panda-sharp</Author>
		<Solution>Yugen.Toolkit</Solution>
		<Project>Yugen.Toolkit.Uwp.Audio.Controls</Project>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Win2D.uwp" Version="1.28.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Yugen.Toolkit.Standard\Yugen.Toolkit.Standard.csproj" />
		<ProjectReference Include="..\Yugen.Toolkit.Uwp\Yugen.Toolkit.Uwp.csproj" />
	</ItemGroup>
</Project>